---
- name: Let Mysql startup
  pause:
    seconds: 30

#- debug:
#    var: hostvars.mysqlmaster.master_status_binlog

#- debug:
#    var: hostvars.mysqlmaster.master_status_position

#- debug:
#    var: hostvars.mysqlmaster.ansible_default_ipv4.address

- name: change master to mysqlmaster
  shell: > 
    podman exec -it {{ inventory_hostname_short }} \ 
    mysql -uroot -ppassword \
    -e "CHANGE MASTER TO MASTER_HOST='{{ hostvars.mysqlmaster.ansible_default_ipv4.address }}',
    MASTER_USER='slave_user',
    MASTER_PASSWORD='password',
    MASTER_LOG_FILE='{{ hostvars.mysqlmaster.master_status_binlog }}',
    MASTER_LOG_POS={{ hostvars.mysqlmaster.master_status_position }};"

- name: Activate slave 
  shell: >
   podman exec -it {{ inventory_hostname_short }} \
   mysql -uroot -ppassword -e "START SLAVE;"