---

- name: Copiar mysql dump 
  copy:
    src: /tmp/slave.sql
    dest: /tmp/slave.sql

- name: Crear BD
  community.mysql.mysql_db:
    login_user: root
    login_password: ""
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: tastydb
    state: present

- name: Restore database
  community.mysql.mysql_db:
    login_user: root
    login_password: ""
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: tastydb
    state: import
    target: /tmp/slave.sql/slave.sql/mysqlmaster/tmp/dump.sql

- name: Configurar Server ID
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '\#server-id.*= .*'
    insertafter: '\#server-id.*= .*'
    line: 'server-id = 2'

- name: Configurar LogBin
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '\#log_bin.*=.*'
    insertafter: '\#log_bin.*=.*'
    line: 'log_bin = /var/log/mysql/mysql-bin.log'

- name: Configurar BinLogdb
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '\#binlog_do_db.*=.*'
    insertafter: '\#binlog_do_db.*=.*'
    line: 'binlog_do_db = tastydb'

- name: Configurar Relay Log
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '\#relay_log.*=.*'
    insertafter: '\#relay_log.*=.*'
    line: 'relay-log = /var/log/mysql/mysql-relay-bin.log'

- name: Reiniciar Mysql
  action: service name=mysql state=restarted