---

- name: Instalacion de Apache con modulos
  package: 
    name: "{{ paquete_apache }}"
    state: latest

- name: Restart Apache
  action: service name=apache2 state=restarted
    
- name: Copiar index.html
  template: 
    src: index.html.j2
    dest: /var/www/html/index.html
    mode: 0777 #Esto es pecado mortal, solo como testing


- name: Actualizar repositorios
  command: sudo apt-get update
